displayName: Maintenance page
summary: Show visitors a maintenance page.
iconPath: assets/icon.png

type: middleware
import: github.com/programic/traefik-maintenance-plugin

testData:
  informUrl: "https://programic.com/themes/programic/assets/hosts.json"