version: '3.8'

services:
  traefik:
    image: traefik:v2.9
    restart: unless-stopped
    ports:
      - 80:80
      - 8080:8080
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/dynamic:/etc/traefik/dynamic
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./:/plugins-local/src/github.com/programic/traefik-maintenance-plugin

  whoami:
    image: traefik/whoami
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.test`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.routers.whoami.middlewares=my-maintenance@file"
    networks:
      - web

networks:
  web:
    external: true