# log:
#   level: DEBUG

experimental:
  localPlugins:
    maintenance:
      moduleName: github.com/programic/traefik-maintenance-plugin

api:
  insecure: true

providers:
  docker:
    watch: true
    exposedByDefault: false
    network: web
  file:
    directory: /etc/traefik/dynamic

entrypoints:
  web:
    address: :80